# whitelist
#branches:
#  only:
#    - master
#    - develop

language:
  - node_js

node_js:
  - '5'

before_install:
  # Setup `Chrome` instance.
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - npm run tsc
  - npm run scss
script:
  - npm run e2e-test